/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/common/auth/login-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 密码登录（v0.3：deviceType 由前端 App 配置写死） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        identifier: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                                phone: string | null;
                                email: string | null;
                                name: string | null;
                                avatarUrl: string | null;
                                /** @enum {string} */
                                status: "ACTIVE" | "SUSPENDED" | "DELETED";
                            };
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description LOGIN_FAILED */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 注册（v0.3 冲突 11：smsCode 可选，W6 强制） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        phone: string;
                        /** Format: email */
                        email: string;
                        password: string;
                        name?: string;
                        smsCode?: string;
                    };
                };
            };
            responses: {
                /** @description 注册成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                                phone: string | null;
                                email: string | null;
                                name: string | null;
                                avatarUrl: string | null;
                                /** @enum {string} */
                                status: "ACTIVE" | "SUSPENDED" | "DELETED";
                            };
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description PHONE_ALREADY_REGISTERED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description REFRESH_TOKEN_INVALID */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description v0.3 决策 F：必传 refreshToken，服务端加 Redis 黑名单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description 登出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/send-sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description SMS stub（固定 123456，标 [SMS_STUB]），W6 切东帝汶本地 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        phone: string;
                        /** @enum {string} */
                        type: "REGISTER" | "LOGIN" | "RESET_PASSWORD";
                    };
                };
            };
            responses: {
                /** @description 已发送（stub） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            expireIn: number;
                        };
                    };
                };
                /** @description SMS_RATE_LIMIT */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取个人信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            phone: string | null;
                            /** Format: email */
                            email: string | null;
                            name: string | null;
                            avatarUrl: string | null;
                            /** @enum {string} */
                            role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                            /** @enum {string} */
                            status: "ACTIVE" | "SUSPENDED" | "DELETED";
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取店铺信息（单一商家） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: {
                                [key: string]: string;
                            };
                            /** Format: uri */
                            logoUrl: string | null;
                            phone: string;
                            address: string;
                            /** @enum {string} */
                            status: "ACTIVE" | "INACTIVE";
                            businessHours: string | null;
                            announcement?: {
                                [key: string]: string;
                            };
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 仓库列表（多仓库 5-10 个） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            code: string;
                            name: {
                                [key: string]: string;
                            };
                            coverageArea: {
                                /** @enum {string} */
                                type: "Polygon";
                                coordinates: number[][][];
                            } | null;
                            centerPoint: {
                                /** @enum {string} */
                                type: "Point";
                                coordinates: number[];
                            } | null;
                            centerLat: number | null;
                            centerLng: number | null;
                            address: string;
                            operatingHours: {
                                mon?: {
                                    open: string;
                                    close: string;
                                };
                                tue?: {
                                    open: string;
                                    close: string;
                                };
                                wed?: {
                                    open: string;
                                    close: string;
                                };
                                thu?: {
                                    open: string;
                                    close: string;
                                };
                                fri?: {
                                    open: string;
                                    close: string;
                                };
                                sat?: {
                                    open: string;
                                    close: string;
                                };
                                sun?: {
                                    open: string;
                                    close: string;
                                };
                            } | null;
                            /** @default 0 */
                            deliveryFee: number;
                            /** @default true */
                            isActive: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/warehouses/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 按经纬度匹配最近仓库（PostGIS ST_Within） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        lat: number;
                        lng: number;
                    };
                };
            };
            responses: {
                /** @description 匹配成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            code: string;
                            name: {
                                [key: string]: string;
                            };
                            coverageArea: {
                                /** @enum {string} */
                                type: "Polygon";
                                coordinates: number[][][];
                            } | null;
                            centerPoint: {
                                /** @enum {string} */
                                type: "Point";
                                coordinates: number[];
                            } | null;
                            centerLat: number | null;
                            centerLng: number | null;
                            address: string;
                            operatingHours: {
                                mon?: {
                                    open: string;
                                    close: string;
                                };
                                tue?: {
                                    open: string;
                                    close: string;
                                };
                                wed?: {
                                    open: string;
                                    close: string;
                                };
                                thu?: {
                                    open: string;
                                    close: string;
                                };
                                fri?: {
                                    open: string;
                                    close: string;
                                };
                                sat?: {
                                    open: string;
                                    close: string;
                                };
                                sun?: {
                                    open: string;
                                    close: string;
                                };
                            } | null;
                            /** @default 0 */
                            deliveryFee: number;
                            /** @default true */
                            isActive: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description OUT_OF_DELIVERY_RANGE */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 创建订单（同步事务 MVP，自动匹配仓库 + orderNo 16 位） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        addressId: string;
                        items: {
                            /** Format: uuid */
                            skuId: string;
                            quantity: number;
                        }[];
                        remark?: string;
                        /** @enum {string} */
                        paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                    };
                };
            };
            responses: {
                /** @description 订单创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            orderNo: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string;
                            /** @enum {string} */
                            status: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                productId: string;
                                /** Format: uuid */
                                skuId: string;
                                productName: string;
                                productImage: string;
                                skuName: string;
                                unitPrice: number;
                                quantity: number;
                                subtotal: number;
                            }[];
                            totalAmount: number;
                            deliveryFee: number;
                            /** @default 0 */
                            discountAmount: number;
                            payableAmount: number;
                            deliveryAddress: {
                                name: string;
                                phone: string;
                                detail: string;
                                lat: number | null;
                                lng: number | null;
                            };
                            remark: string | null;
                            /** Format: uuid */
                            riderId: string | null;
                            /** @enum {string} */
                            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                            /** @enum {string} */
                            paymentStatus: "UNPAID" | "PAID" | "REFUNDED";
                            /** Format: date-time */
                            paidAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            confirmedAt: string | null;
                            /** Format: date-time */
                            pickedAt: string | null;
                            /** Format: date-time */
                            deliveringAt: string | null;
                            /** Format: date-time */
                            deliveredAt: string | null;
                            /** Format: date-time */
                            cancelledAt: string | null;
                            cancelReason: string | null;
                        };
                    };
                };
                /** @description STOCK_NOT_ENOUGH */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JwtPayload: {
            /** Format: uuid */
            sub: string;
            /** @enum {string} */
            role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
            /** @enum {string} */
            deviceType: "client_app" | "rider_app" | "admin_web";
            iat: number;
            exp: number;
            /** Format: uuid */
            jti: string;
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        LoginRequest: {
            identifier: string;
            password: string;
        };
        LoginResponseData: {
            user: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                phone: string | null;
                email: string | null;
                name: string | null;
                avatarUrl: string | null;
                /** @enum {string} */
                status: "ACTIVE" | "SUSPENDED" | "DELETED";
            };
            accessToken: string;
            refreshToken: string;
        };
        RegisterRequest: {
            phone: string;
            /** Format: email */
            email: string;
            password: string;
            name?: string;
            smsCode?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RefreshResponseData: {
            accessToken: string;
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        SendSmsRequest: {
            phone: string;
            /** @enum {string} */
            type: "REGISTER" | "LOGIN" | "RESET_PASSWORD";
        };
        SendSmsResponseData: {
            expireIn: number;
        };
        ResetPasswordRequest: {
            /** Format: email */
            email: string;
            code: string;
            newPassword: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            phone: string | null;
            /** Format: email */
            email: string | null;
            name: string | null;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED" | "DELETED";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateProfileRequest: {
            name?: string;
            /** Format: uri */
            avatarUrl?: string;
        };
        ChangePasswordRequest: {
            oldPassword: string;
            newPassword: string;
        };
        Shop: {
            /** Format: uuid */
            id: string;
            name: {
                [key: string]: string;
            };
            /** Format: uri */
            logoUrl: string | null;
            phone: string;
            address: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            businessHours: string | null;
            announcement?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateShopRequest: {
            name?: {
                [key: string]: string;
            };
            /** Format: uri */
            logoUrl?: string | null;
            phone?: string;
            address?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            businessHours?: string | null;
            announcement?: {
                [key: string]: string;
            };
        };
        Warehouse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: {
                [key: string]: string;
            };
            coverageArea: {
                /** @enum {string} */
                type: "Polygon";
                coordinates: number[][][];
            } | null;
            centerPoint: {
                /** @enum {string} */
                type: "Point";
                coordinates: number[];
            } | null;
            centerLat: number | null;
            centerLng: number | null;
            address: string;
            operatingHours: {
                mon?: {
                    open: string;
                    close: string;
                };
                tue?: {
                    open: string;
                    close: string;
                };
                wed?: {
                    open: string;
                    close: string;
                };
                thu?: {
                    open: string;
                    close: string;
                };
                fri?: {
                    open: string;
                    close: string;
                };
                sat?: {
                    open: string;
                    close: string;
                };
                sun?: {
                    open: string;
                    close: string;
                };
            } | null;
            /** @default 0 */
            deliveryFee: number;
            /** @default true */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpsertWarehouseRequest: {
            code?: string;
            name: {
                [key: string]: string;
            };
            coverageArea: {
                /** @enum {string} */
                type: "Polygon";
                coordinates: number[][][];
            } | null;
            centerLat: number;
            centerLng: number;
            address: string;
            operatingHours: {
                mon?: {
                    open: string;
                    close: string;
                };
                tue?: {
                    open: string;
                    close: string;
                };
                wed?: {
                    open: string;
                    close: string;
                };
                thu?: {
                    open: string;
                    close: string;
                };
                fri?: {
                    open: string;
                    close: string;
                };
                sat?: {
                    open: string;
                    close: string;
                };
                sun?: {
                    open: string;
                    close: string;
                };
            } | null;
            deliveryFee: number;
            isActive: boolean;
        };
        MatchWarehouseRequest: {
            lat: number;
            lng: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            orderNo: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            warehouseId: string;
            /** @enum {string} */
            status: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
            items: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                productId: string;
                /** Format: uuid */
                skuId: string;
                productName: string;
                productImage: string;
                skuName: string;
                unitPrice: number;
                quantity: number;
                subtotal: number;
            }[];
            totalAmount: number;
            deliveryFee: number;
            /** @default 0 */
            discountAmount: number;
            payableAmount: number;
            deliveryAddress: {
                name: string;
                phone: string;
                detail: string;
                lat: number | null;
                lng: number | null;
            };
            remark: string | null;
            /** Format: uuid */
            riderId: string | null;
            /** @enum {string} */
            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
            /** @enum {string} */
            paymentStatus: "UNPAID" | "PAID" | "REFUNDED";
            /** Format: date-time */
            paidAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            confirmedAt: string | null;
            /** Format: date-time */
            pickedAt: string | null;
            /** Format: date-time */
            deliveringAt: string | null;
            /** Format: date-time */
            deliveredAt: string | null;
            /** Format: date-time */
            cancelledAt: string | null;
            cancelReason: string | null;
        };
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            skuId: string;
            productName: string;
            productImage: string;
            skuName: string;
            unitPrice: number;
            quantity: number;
            subtotal: number;
        };
        CreateOrderRequest: {
            /** Format: uuid */
            addressId: string;
            items: {
                /** Format: uuid */
                skuId: string;
                quantity: number;
            }[];
            remark?: string;
            /** @enum {string} */
            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
        };
        CancelOrderRequest: {
            reason: string;
        };
        OrderNo: string;
        /** @enum {string} */
        PaymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
        /** @enum {string} */
        OrderStatus: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
