/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/common/auth/login-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 密码登录（v0.3：deviceType 由前端 App 配置写死） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        identifier: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                                phone: string | null;
                                email: string | null;
                                name: string | null;
                                avatarUrl: string | null;
                                /** @enum {string} */
                                status: "ACTIVE" | "SUSPENDED" | "DELETED";
                            };
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description LOGIN_FAILED */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 注册（v0.3 冲突 11：smsCode 可选，W6 强制） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        phone: string;
                        /** Format: email */
                        email: string;
                        password: string;
                        name?: string;
                        smsCode?: string;
                    };
                };
            };
            responses: {
                /** @description 注册成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                                phone: string | null;
                                email: string | null;
                                name: string | null;
                                avatarUrl: string | null;
                                /** @enum {string} */
                                status: "ACTIVE" | "SUSPENDED" | "DELETED";
                            };
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description PHONE_ALREADY_REGISTERED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description REFRESH_TOKEN_INVALID */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description v0.3 决策 F：必传 refreshToken，服务端加 Redis 黑名单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description 登出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/auth/send-sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description SMS stub（固定 123456，标 [SMS_STUB]），W6 切东帝汶本地 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        phone: string;
                        /** @enum {string} */
                        type: "REGISTER" | "LOGIN" | "RESET_PASSWORD";
                    };
                };
            };
            responses: {
                /** @description 已发送（stub） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            expireIn: number;
                        };
                    };
                };
                /** @description SMS_RATE_LIMIT */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取个人信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            phone: string | null;
                            /** Format: email */
                            email: string | null;
                            name: string | null;
                            avatarUrl: string | null;
                            /** @enum {string} */
                            role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                            /** @enum {string} */
                            status: "ACTIVE" | "SUSPENDED" | "DELETED";
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取店铺信息（单一商家） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: {
                                [key: string]: string;
                            };
                            /** Format: uri */
                            logoUrl: string | null;
                            phone: string;
                            address: string;
                            /** @enum {string} */
                            status: "ACTIVE" | "INACTIVE";
                            businessHours: string | null;
                            announcement?: {
                                [key: string]: string;
                            };
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 仓库列表（多仓库 5-10 个） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            code: string;
                            name: {
                                [key: string]: string;
                            };
                            coverageArea: {
                                /** @enum {string} */
                                type: "Polygon";
                                coordinates: number[][][];
                            } | null;
                            centerPoint: {
                                /** @enum {string} */
                                type: "Point";
                                coordinates: number[];
                            } | null;
                            centerLat: number | null;
                            centerLng: number | null;
                            address: string;
                            operatingHours: {
                                mon?: {
                                    open: string;
                                    close: string;
                                };
                                tue?: {
                                    open: string;
                                    close: string;
                                };
                                wed?: {
                                    open: string;
                                    close: string;
                                };
                                thu?: {
                                    open: string;
                                    close: string;
                                };
                                fri?: {
                                    open: string;
                                    close: string;
                                };
                                sat?: {
                                    open: string;
                                    close: string;
                                };
                                sun?: {
                                    open: string;
                                    close: string;
                                };
                            } | null;
                            /** @default 0 */
                            deliveryFee: number;
                            /** @default true */
                            isActive: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/warehouses/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 按经纬度匹配最近仓库（PostGIS ST_Within） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        lat: number;
                        lng: number;
                    };
                };
            };
            responses: {
                /** @description 匹配成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            code: string;
                            name: {
                                [key: string]: string;
                            };
                            coverageArea: {
                                /** @enum {string} */
                                type: "Polygon";
                                coordinates: number[][][];
                            } | null;
                            centerPoint: {
                                /** @enum {string} */
                                type: "Point";
                                coordinates: number[];
                            } | null;
                            centerLat: number | null;
                            centerLng: number | null;
                            address: string;
                            operatingHours: {
                                mon?: {
                                    open: string;
                                    close: string;
                                };
                                tue?: {
                                    open: string;
                                    close: string;
                                };
                                wed?: {
                                    open: string;
                                    close: string;
                                };
                                thu?: {
                                    open: string;
                                    close: string;
                                };
                                fri?: {
                                    open: string;
                                    close: string;
                                };
                                sat?: {
                                    open: string;
                                    close: string;
                                };
                                sun?: {
                                    open: string;
                                    close: string;
                                };
                            } | null;
                            /** @default 0 */
                            deliveryFee: number;
                            /** @default true */
                            isActive: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description OUT_OF_DELIVERY_RANGE */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 客户端订单列表（按状态筛选 + 游标分页） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 订单列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            orderNo: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string;
                            /** @enum {string} */
                            status: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                productId: string;
                                /** Format: uuid */
                                skuId: string;
                                productName: string;
                                productImage: string;
                                skuName: string;
                                unitPrice: number;
                                quantity: number;
                                subtotal: number;
                            }[];
                            totalAmount: number;
                            deliveryFee: number;
                            /** @default 0 */
                            discountAmount: number;
                            payableAmount: number;
                            deliveryAddress: {
                                name: string;
                                phone: string;
                                detail: string;
                                lat: number | null;
                                lng: number | null;
                            };
                            remark: string | null;
                            /** Format: uuid */
                            riderId: string | null;
                            /** @enum {string} */
                            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                            /** @enum {string} */
                            paymentStatus: "UNPAID" | "PAID" | "REFUNDED";
                            /** Format: date-time */
                            paidAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            confirmedAt: string | null;
                            /** Format: date-time */
                            pickedAt: string | null;
                            /** Format: date-time */
                            deliveringAt: string | null;
                            /** Format: date-time */
                            deliveredAt: string | null;
                            /** Format: date-time */
                            cancelledAt: string | null;
                            cancelReason: string | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** @description 创建订单（同步事务 MVP，自动匹配仓库 + orderNo 16 位） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        addressId: string;
                        items: {
                            /** Format: uuid */
                            skuId: string;
                            quantity: number;
                        }[];
                        remark?: string;
                        /** @enum {string} */
                        paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                    };
                };
            };
            responses: {
                /** @description 订单创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            orderNo: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string;
                            /** @enum {string} */
                            status: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                productId: string;
                                /** Format: uuid */
                                skuId: string;
                                productName: string;
                                productImage: string;
                                skuName: string;
                                unitPrice: number;
                                quantity: number;
                                subtotal: number;
                            }[];
                            totalAmount: number;
                            deliveryFee: number;
                            /** @default 0 */
                            discountAmount: number;
                            payableAmount: number;
                            deliveryAddress: {
                                name: string;
                                phone: string;
                                detail: string;
                                lat: number | null;
                                lng: number | null;
                            };
                            remark: string | null;
                            /** Format: uuid */
                            riderId: string | null;
                            /** @enum {string} */
                            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                            /** @enum {string} */
                            paymentStatus: "UNPAID" | "PAID" | "REFUNDED";
                            /** Format: date-time */
                            paidAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            confirmedAt: string | null;
                            /** Format: date-time */
                            pickedAt: string | null;
                            /** Format: date-time */
                            deliveringAt: string | null;
                            /** Format: date-time */
                            deliveredAt: string | null;
                            /** Format: date-time */
                            cancelledAt: string | null;
                            cancelReason: string | null;
                        };
                    };
                };
                /** @description STOCK_NOT_ENOUGH */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 订单详情（含 items + events） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 订单详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            orderNo: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string;
                            /** @enum {string} */
                            status: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                productId: string;
                                /** Format: uuid */
                                skuId: string;
                                productName: string;
                                productImage: string;
                                skuName: string;
                                unitPrice: number;
                                quantity: number;
                                subtotal: number;
                            }[];
                            totalAmount: number;
                            deliveryFee: number;
                            /** @default 0 */
                            discountAmount: number;
                            payableAmount: number;
                            deliveryAddress: {
                                name: string;
                                phone: string;
                                detail: string;
                                lat: number | null;
                                lng: number | null;
                            };
                            remark: string | null;
                            /** Format: uuid */
                            riderId: string | null;
                            /** @enum {string} */
                            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                            /** @enum {string} */
                            paymentStatus: "UNPAID" | "PAID" | "REFUNDED";
                            /** Format: date-time */
                            paidAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            confirmedAt: string | null;
                            /** Format: date-time */
                            pickedAt: string | null;
                            /** Format: date-time */
                            deliveringAt: string | null;
                            /** Format: date-time */
                            deliveredAt: string | null;
                            /** Format: date-time */
                            cancelledAt: string | null;
                            cancelReason: string | null;
                        };
                    };
                };
                /** @description ORDER_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 取消订单（用户自助，PENDING_* / CONFIRMED 可取消） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description 取消成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ORDER_STATUS_NOT_CANCELLABLE */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取购物车（按用户 1 份，含 items + 选中金额汇总） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 购物车详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string | null;
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                skuId: string;
                                /** Format: uuid */
                                productId: string;
                                productName: {
                                    [key: string]: string;
                                };
                                productImage: string;
                                skuName: {
                                    [key: string]: string;
                                };
                                unitPrice: number;
                                quantity: number;
                                isSelected: boolean;
                                /** Format: date-time */
                                addedAt: string;
                            }[];
                            selectedSubtotal: number;
                            totalSubtotal: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 加购（同 sku 累加数量 + 刷新价格快照） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        skuId: string;
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description 加购后的购物车 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string | null;
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                skuId: string;
                                /** Format: uuid */
                                productId: string;
                                productName: {
                                    [key: string]: string;
                                };
                                productImage: string;
                                skuName: {
                                    [key: string]: string;
                                };
                                unitPrice: number;
                                quantity: number;
                                isSelected: boolean;
                                /** Format: date-time */
                                addedAt: string;
                            }[];
                            selectedSubtotal: number;
                            totalSubtotal: number;
                        };
                    };
                };
                /** @description SKU_INACTIVE */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/cart/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description 删除购物车项 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除后的购物车 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string | null;
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                skuId: string;
                                /** Format: uuid */
                                productId: string;
                                productName: {
                                    [key: string]: string;
                                };
                                productImage: string;
                                skuName: {
                                    [key: string]: string;
                                };
                                unitPrice: number;
                                quantity: number;
                                isSelected: boolean;
                                /** Format: date-time */
                                addedAt: string;
                            }[];
                            selectedSubtotal: number;
                            totalSubtotal: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description 修改购物车项数量 / 选中状态 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        quantity?: number;
                        isSelected?: boolean;
                    };
                };
            };
            responses: {
                /** @description 修改后的购物车 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            userId: string;
                            /** Format: uuid */
                            warehouseId: string | null;
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                skuId: string;
                                /** Format: uuid */
                                productId: string;
                                productName: {
                                    [key: string]: string;
                                };
                                productImage: string;
                                skuName: {
                                    [key: string]: string;
                                };
                                unitPrice: number;
                                quantity: number;
                                isSelected: boolean;
                                /** Format: date-time */
                                addedAt: string;
                            }[];
                            selectedSubtotal: number;
                            totalSubtotal: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/client/cart/checkout-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 结算前预览（按地址匹配仓库 + 库存/价格校验 + 金额汇总） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        addressId: string;
                    };
                };
            };
            responses: {
                /** @description 结算预览 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                skuId: string;
                                /** Format: uuid */
                                productId: string;
                                productName: {
                                    [key: string]: string;
                                };
                                productImage: string;
                                skuName: {
                                    [key: string]: string;
                                };
                                unitPrice: number;
                                quantity: number;
                                isSelected: boolean;
                                /** Format: date-time */
                                addedAt: string;
                            }[];
                            warehouseMatch: {
                                /** Format: uuid */
                                id: string;
                                code: string;
                                deliveryFee: number;
                            } | null;
                            itemsSubtotal: number;
                            deliveryFee: number;
                            payableAmount: number;
                            warnings: string[];
                        };
                    };
                };
                /** @description NO_SELECTED_ITEMS / OUT_OF_DELIVERY_RANGE */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/payments/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 查询订单支付状态（含 mock/stub 标识） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PaymentIntent 详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            orderId: string;
                            /** @enum {string} */
                            method: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                            /** @enum {string} */
                            status: "UNPAID" | "PAID" | "REFUNDED";
                            amount: number;
                            transactionId: string | null;
                            clientSecret: string | null;
                            /** Format: uri */
                            receiptUrl: string | null;
                            mockFlag: boolean;
                            /** Format: date-time */
                            paidAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description PAYMENT_INTENT_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/payments/{orderId}/mock-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description dev/staging 模拟第三方支付成功回调（仅 WECHAT/PAYPAL/STRIPE） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 回调成功，订单自动进 CONFIRMED */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description METHOD_NOT_ALLOWED / DISABLED_IN_PROD */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/payments/{orderId}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 银行转账凭证上传（BANK_TRANSFER 专用） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        receiptUrl: string;
                    };
                };
            };
            responses: {
                /** @description 凭证已上传，状态进 PROCESSING 等审核 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            orderId: string;
                            /** @enum {string} */
                            method: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
                            /** @enum {string} */
                            status: "UNPAID" | "PAID" | "REFUNDED";
                            amount: number;
                            transactionId: string | null;
                            clientSecret: string | null;
                            /** Format: uri */
                            receiptUrl: string | null;
                            mockFlag: boolean;
                            /** Format: date-time */
                            paidAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/payments/{orderId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 客户端轮询查到 PAID 后触发订单确认 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 订单已确认 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description PAYMENT_NOT_PAID */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JwtPayload: {
            /** Format: uuid */
            sub: string;
            /** @enum {string} */
            role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
            /** @enum {string} */
            deviceType: "client_app" | "rider_app" | "admin_web";
            iat: number;
            exp: number;
            /** Format: uuid */
            jti: string;
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        LoginRequest: {
            identifier: string;
            password: string;
        };
        LoginResponseData: {
            user: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
                phone: string | null;
                email: string | null;
                name: string | null;
                avatarUrl: string | null;
                /** @enum {string} */
                status: "ACTIVE" | "SUSPENDED" | "DELETED";
            };
            accessToken: string;
            refreshToken: string;
        };
        RegisterRequest: {
            phone: string;
            /** Format: email */
            email: string;
            password: string;
            name?: string;
            smsCode?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RefreshResponseData: {
            accessToken: string;
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        SendSmsRequest: {
            phone: string;
            /** @enum {string} */
            type: "REGISTER" | "LOGIN" | "RESET_PASSWORD";
        };
        SendSmsResponseData: {
            expireIn: number;
        };
        ResetPasswordRequest: {
            /** Format: email */
            email: string;
            code: string;
            newPassword: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            phone: string | null;
            /** Format: email */
            email: string | null;
            name: string | null;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "super_admin" | "customer" | "rider" | "warehouse_staff" | "customer_service";
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED" | "DELETED";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateProfileRequest: {
            name?: string;
            /** Format: uri */
            avatarUrl?: string;
        };
        ChangePasswordRequest: {
            oldPassword: string;
            newPassword: string;
        };
        Shop: {
            /** Format: uuid */
            id: string;
            name: {
                [key: string]: string;
            };
            /** Format: uri */
            logoUrl: string | null;
            phone: string;
            address: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            businessHours: string | null;
            announcement?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateShopRequest: {
            name?: {
                [key: string]: string;
            };
            /** Format: uri */
            logoUrl?: string | null;
            phone?: string;
            address?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            businessHours?: string | null;
            announcement?: {
                [key: string]: string;
            };
        };
        Warehouse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: {
                [key: string]: string;
            };
            coverageArea: {
                /** @enum {string} */
                type: "Polygon";
                coordinates: number[][][];
            } | null;
            centerPoint: {
                /** @enum {string} */
                type: "Point";
                coordinates: number[];
            } | null;
            centerLat: number | null;
            centerLng: number | null;
            address: string;
            operatingHours: {
                mon?: {
                    open: string;
                    close: string;
                };
                tue?: {
                    open: string;
                    close: string;
                };
                wed?: {
                    open: string;
                    close: string;
                };
                thu?: {
                    open: string;
                    close: string;
                };
                fri?: {
                    open: string;
                    close: string;
                };
                sat?: {
                    open: string;
                    close: string;
                };
                sun?: {
                    open: string;
                    close: string;
                };
            } | null;
            /** @default 0 */
            deliveryFee: number;
            /** @default true */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpsertWarehouseRequest: {
            code?: string;
            name: {
                [key: string]: string;
            };
            coverageArea: {
                /** @enum {string} */
                type: "Polygon";
                coordinates: number[][][];
            } | null;
            centerLat: number;
            centerLng: number;
            address: string;
            operatingHours: {
                mon?: {
                    open: string;
                    close: string;
                };
                tue?: {
                    open: string;
                    close: string;
                };
                wed?: {
                    open: string;
                    close: string;
                };
                thu?: {
                    open: string;
                    close: string;
                };
                fri?: {
                    open: string;
                    close: string;
                };
                sat?: {
                    open: string;
                    close: string;
                };
                sun?: {
                    open: string;
                    close: string;
                };
            } | null;
            deliveryFee: number;
            isActive: boolean;
        };
        MatchWarehouseRequest: {
            lat: number;
            lng: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            orderNo: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            warehouseId: string;
            /** @enum {string} */
            status: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
            items: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                productId: string;
                /** Format: uuid */
                skuId: string;
                productName: string;
                productImage: string;
                skuName: string;
                unitPrice: number;
                quantity: number;
                subtotal: number;
            }[];
            totalAmount: number;
            deliveryFee: number;
            /** @default 0 */
            discountAmount: number;
            payableAmount: number;
            deliveryAddress: {
                name: string;
                phone: string;
                detail: string;
                lat: number | null;
                lng: number | null;
            };
            remark: string | null;
            /** Format: uuid */
            riderId: string | null;
            /** @enum {string} */
            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
            /** @enum {string} */
            paymentStatus: "UNPAID" | "PAID" | "REFUNDED";
            /** Format: date-time */
            paidAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            confirmedAt: string | null;
            /** Format: date-time */
            pickedAt: string | null;
            /** Format: date-time */
            deliveringAt: string | null;
            /** Format: date-time */
            deliveredAt: string | null;
            /** Format: date-time */
            cancelledAt: string | null;
            cancelReason: string | null;
        };
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            skuId: string;
            productName: string;
            productImage: string;
            skuName: string;
            unitPrice: number;
            quantity: number;
            subtotal: number;
        };
        CreateOrderRequest: {
            /** Format: uuid */
            addressId: string;
            items: {
                /** Format: uuid */
                skuId: string;
                quantity: number;
            }[];
            remark?: string;
            /** @enum {string} */
            paymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
        };
        CancelOrderRequest: {
            reason: string;
        };
        OrderNo: string;
        /** @enum {string} */
        PaymentMethod: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
        /** @enum {string} */
        OrderStatus: "PENDING_PAYMENT" | "PENDING_CONFIRM" | "CONFIRMED" | "PICKED" | "OUT_FOR_DELIVERY" | "DELIVERED_PAID" | "DELIVERED" | "DELIVERED_UNPAID" | "COMPLETED" | "CANCELLED";
        Cart: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            warehouseId: string | null;
            items: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                skuId: string;
                /** Format: uuid */
                productId: string;
                productName: {
                    [key: string]: string;
                };
                productImage: string;
                skuName: {
                    [key: string]: string;
                };
                unitPrice: number;
                quantity: number;
                isSelected: boolean;
                /** Format: date-time */
                addedAt: string;
            }[];
            selectedSubtotal: number;
            totalSubtotal: number;
        };
        CartItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            skuId: string;
            /** Format: uuid */
            productId: string;
            productName: {
                [key: string]: string;
            };
            productImage: string;
            skuName: {
                [key: string]: string;
            };
            unitPrice: number;
            quantity: number;
            isSelected: boolean;
            /** Format: date-time */
            addedAt: string;
        };
        AddCartItemRequest: {
            /** Format: uuid */
            skuId: string;
            quantity: number;
        };
        UpdateCartItemRequest: {
            quantity?: number;
            isSelected?: boolean;
        };
        CheckoutPreviewRequest: {
            /** Format: uuid */
            addressId: string;
        };
        CheckoutPreview: {
            items: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                skuId: string;
                /** Format: uuid */
                productId: string;
                productName: {
                    [key: string]: string;
                };
                productImage: string;
                skuName: {
                    [key: string]: string;
                };
                unitPrice: number;
                quantity: number;
                isSelected: boolean;
                /** Format: date-time */
                addedAt: string;
            }[];
            warehouseMatch: {
                /** Format: uuid */
                id: string;
                code: string;
                deliveryFee: number;
            } | null;
            itemsSubtotal: number;
            deliveryFee: number;
            payableAmount: number;
            warnings: string[];
        };
        PaymentIntent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            /** @enum {string} */
            method: "COD" | "BANK_TRANSFER" | "WECHAT" | "PAYPAL" | "STRIPE";
            /** @enum {string} */
            status: "UNPAID" | "PAID" | "REFUNDED";
            amount: number;
            transactionId: string | null;
            clientSecret: string | null;
            /** Format: uri */
            receiptUrl: string | null;
            mockFlag: boolean;
            /** Format: date-time */
            paidAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UploadReceiptRequest: {
            /** Format: uri */
            receiptUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
